# Site settings
port: 80
assets_version: 0.0.0

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost" # the base hostname & protocol for your site
title: "Computer Knowledge - Just more than infinite"
description: "Help, tips and tricks for advance technical users for their help. Some posts also relevant for those facing other problems."

# default author setting
author: Ritesh Shrivastav
author_img: "resources/uploads/codingdash-ritesh.png"
email: ritesh@codingdash.com
twitter_username: codingdash
github_username:  codingdash

# Post settings
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# Sass settings
sass:
    style: :compressed

# syntax-highlighting:
#   enabled : true
#   css: syntax.css