# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
port: 80
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost" # the base hostname & protocol for your site
title: "Technology, design and thoughts"
description: "Personal blog and portfolio of Ritesh Shrivastav"

author: Ritesh Shrivastav
author_img: "resources/uploads/codingdash-ritesh.png"
email: ritesh@codingdash.com
twitter_username: codingdash
github_username:  codingdash


# Post settings
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# Sass settings
sass:
    style: :compressed